env:
  browser: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2021
  sourceType: module
rules: {
  no-console: 'error',
  indent: ['error', 4],
  import/no-extraneous-dependencies: ["error", {"devDependencies": true}],
  no-unused-vars: 0
}
