name: PHP Composer

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install composer
      run: composer install

    - name: Yarn
      run: yarn --ignore-engines install

    - name: code_quality
      run: |
        ./vendor/bin/phpcs
        ./vendor/bin/phpstan analyse src --level max
        ./vendor/bin/phpmd src text phpmd.xml
        ./node_modules/.bin/eslint assets/js
    
    - name: phpunit
      run: bin/phpunit